### ISSUE TITLE
ppo and entropy

### ISSUE THREAD

**Issue by feidieufo** [Yonv1943/DL_RL_Zoo#4]
In your AgentZoo.py class AgentGAE
you estimate policy entropy use mean
```
            # surrogate objective of TRPO
            ratio = (new_log_prob - old_log_prob).exp()
            surrogate_obj0 = advantage * ratio
            surrogate_obj1 = advantage * ratio.clamp(1 - clip, 1 + clip)
            surrogate_obj = -torch.min(surrogate_obj0, surrogate_obj1).mean()
            # policy entropy
            loss_entropy = (new_log_prob.exp() * new_log_prob).mean()
``` 
But in the definition of entropy, you should use sum
I want to know the difference of mean and sum to estimate policy entropy.
What impact will they have on the algorithm.

**Comment by Yonv1943** [comment]
I'm still learning English. Pardon. 
**It the same that use mean() or sum(). But use sum() may cause exploding gradient problem.**

You said `you should use sum` means: 
    surrogate_obj = -torch.min(surrogate_obj0, surrogate_obj1).mean()
    loss_entropy = (new_log_prob.exp() * new_log_prob).mean()
should be:
    surrogate_obj = -torch.min(surrogate_obj0, surrogate_obj1).sum()
    loss_entropy = (new_log_prob.exp() * new_log_prob).sum()

**It the same that use mean() or sum()**. See the below:
    surrogate_obj.mean() * batch_size == surrogate_obj.sum()
    loss_entropy.mean() * batch_size == loss_entropy.sum()
Although use sum() is a little faster than mean(), I use mean().
Because sometimes **use sum() will cause exploding gradient problem** when batch_size is too large.

**Comment by feidieufo** [comment]
> I'm still learning English. Pardon.
> **It the same that use mean() or sum(). But use sum() may cause exploding gradient problem.**
> 
> You said `you should use sum` means:
> 
> ```
> surrogate_obj = -torch.min(surrogate_obj0, surrogate_obj1).mean()
> loss_entropy = (new_log_prob.exp() * new_log_prob).mean()
> ```
> 
> should be:
> 
> ```
> surrogate_obj = -torch.min(surrogate_obj0, surrogate_obj1).sum()
> loss_entropy = (new_log_prob.exp() * new_log_prob).sum()
> ```
> 
> **It the same that use mean() or sum()**. See the below:
> 
> ```
> surrogate_obj.mean() * batch_size == surrogate_obj.sum()
> loss_entropy.mean() * batch_size == loss_entropy.sum()
> ```
> 
> Although use sum() is a little faster than mean(), I use mean().
> Because sometimes **use sum() will cause exploding gradient problem** when `batch_size` is too large.

Thank you for your reply
