### ISSUE TITLE
BufferArray bug: sampling range not updated

### ISSUE THREAD

**Issue by zzR2718** [Yonv1943/DL_RL_Zoo#5]
In class BufferArray, random_sample(), the indices are sampled from self.now_len, which does not change as new memory is added. This would result in training on old initial memories unless the whole buffer is full and the index starts from 0 again.

Only small modifications needed, but this can be critical sometimes.

**Comment by zzR2718** [comment]
Sorry I didn't notice that it actually did update via calling buffer.init_before_sampling() outside.

**Comment by Yonv1943** [comment]
Maybe I should write `buffer.init_before_sampling()` into `agent.update_buffer().`
